apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-operator
  namespace: istio-system
spec:
  channel: stable
  installPlanApproval: Automatic
  name: jaeger-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
